packages:
    - tools
    - community
    - cms
    - content
    - shared
    - innerdevelopmentgoals

onlyBuiltDependencies:
    - '@sveltejs/kit'
    - '@tailwindcss/oxide'
    - esbuild
    - sharp

ignoredBuiltDependencies:
    - iframe-resizer
