import { CustomCmsField, ID, MARKDOWN_FIELD, NAME } from './shared'

export const ToolsFields: CustomCmsField[] = [
    ID,
    NAME,
    {
        label: 'Description',
        name: 'description',
        hint: 'Describe how and why this tool helps people practice inner development for sustainable development.',
        i18n: true,
        ...MARKDOWN_FIELD,
    },
    {
        label: 'Actions',
        name: 'actions',
        hint: 'Call to action. Describe one or more ways people can start using this tool to practice inner development for sustainable development.',
        i18n: true,
        ...MARKDOWN_FIELD,
    },
    {
        label: 'Relevant skills',
        name: 'relevancy',
        hint: 'Link related skills from the IDG framework.',
        widget: 'list',
        i18n: true,
        summary: '{{fields.skill}} - {{fields.score}}',
        // minimize_collapsed: true,
        collapsed: true,
        fields: [
            {
                label: 'Skill',
                name: 'skill',
                widget: 'relation',
                collection: 'skills',
                value_field: 'id',
                search_fields: ['name', 'id'],
                display_fields: ['name'],
                i18n: true,
            },
            {
                label: 'Skill relevancy',
                name: 'score',
                hint: 'Score how relevant this skill is (0-100)',
                min: 0,
                max: 100,
                widget: 'number',
                i18n: true,
            },
        ],
    },
    {
        label: 'Tags',
        name: 'tags',
        hint: 'Add tags to make it easier to categorize different tools, and allow filtering the content.',
        multiple: true,
        widget: 'relation',
        collection: 'tags',
        value_field: 'id',
        search_fields: ['name', 'id'],
        display_fields: ['name'],
        i18n: true,
        required: false,
    },
    {
        label: 'Research & Resources',
        name: 'resources',
        hint: 'List relevant research that supports this tool, and other resources that are relevant.',
        i18n: true,
        ...MARKDOWN_FIELD,
        required: false,
    },
    // IDEA: Maybe add custom widget that automatically generates the slug and link, similar to how uniqueId works
    // This would enable content to be created with the CMS rather than having to rely on a build step.
    {
        label: 'Slug',
        name: 'slug',
        i18n: 'duplicate',
        widget: 'uniqueSlug',
    },
    {
        label: 'Link',
        name: 'link',
        i18n: 'duplicate',
        widget: 'hidden',
    },
]
