import { CmsField } from 'netlify-cms-core'
import { STORIES_LEARN_MORE } from '../constants'
import { CustomCmsField, ID, MARKDOWN_ARTICLE, MARKDOWN_LINKS_ONLY, TITLE } from './shared'

export const StoriesFields: CustomCmsField[] = [
    ID,
    TITLE,
    {
        widget: 'image',
        hint: 'The featured image to help give a framing and context to this story',
        i18n: 'duplicate',
        media_folder: '/community/static/images',
        name: 'image',
        choose_url: false,
        label: 'Featured image',
    } as CmsField,
    {
        label: 'Image description (alt text)',
        hint: 'Describe what the image shows. This is important for accessibility.',
        widget: 'string',
        name: 'imageAlt',
        i18n: true,
    },
    {
        label: 'Intro',
        name: 'intro',
        hint: "A short intro to catch the reader's interest.",
        ...MARKDOWN_LINKS_ONLY,
        required: false,
    },
    {
        label: 'Story',
        name: 'story',
        hint: `Your story of how you practiced inner development and how it helped you with sustainable development. [Click here to learn more about IDG.community stories](${STORIES_LEARN_MORE})`,
        ...MARKDOWN_ARTICLE,
    },
    {
        label: 'Relevant dimensions',
        name: 'dimensions',
        hint: 'Link the most relevant dimensions from the IDG framework.',
        widget: 'relation',
        collection: 'dimensions',
        value_field: 'id',
        search_fields: ['name', 'id'],
        display_fields: ['name'],
        i18n: 'duplicate',
        multiple: true,
        required: false,
    },
    {
        label: 'Contributors',
        name: 'contributors',
        hint: 'Give credit to the people behind the story by adding their names.',
        multiple: true,
        widget: 'relation',
        collection: 'contributors',
        value_field: 'id',
        search_fields: ['name', 'id'],
        display_fields: ['name'],
        i18n: true,
        required: false,
    },
    {
        label: 'Tags',
        name: 'tags',
        hint: 'Add tags to make it easier to categorise different stories, and allow filtering the content.',
        multiple: true,
        widget: 'relation',
        collection: 'tags',
        value_field: 'id',
        search_fields: ['name', 'id'],
        display_fields: ['name'],
        i18n: true,
        required: false,
    },
    {
        label: 'Publishing date',
        name: 'publishedAt',
        widget: 'datetime',
        required: false,
        date_format: 'YYYY-MM-DD',
        time_format: '',
        i18n: 'duplicate',
        default: '',
        hint: 'By leaving the publishing date empty, it will not be visible on the webpage.',
    } as CmsField,
    {
        label: 'Slug',
        name: 'slug',
        i18n: 'duplicate',
        widget: 'uniqueSlug',
    },
    {
        label: 'Link',
        name: 'link',
        i18n: 'duplicate',
        widget: 'hidden',
    },
]
