export const AllTopics = [
    'kind',
    'inclusive',
    'feminist',
    'adventurous',
    'emotionally resilient',
    'financially intelligent',
    'self-aware',
    'present',
    'strong',
    'healthy',
    'energized',
    'environmentally conscious',
    'attractive',
    'attentive',
    'fun',
    'digital minimalist',
    'reflective',
]
